# LambdaTest Configuration

# Project and folder configuration
project_id: "01J5B52EZ2S4BNSB7WZMAP3BBE"
folder_id: "01J5B52EZKT9KRZZT9Z1RHFQS0"

# Test Run configuration
assignee: 41319
environment_id: 266986

# Test URL for automation
test_url: "https://demo.lambdatestinternal.com"
