# LambdaTest Configuration

# Project and folder configuration
project_id: "01M1KMVEJG0X49WJ0RPPTW9C09"
folder_id: "01M1KSX4TJSBY00QEPJG4534BF"

# Test Run configuration
assignee: 3452607
configuration_id: 359647

# Test URL for automation
# test_url: "https://demo.lambdatestinternal.com"

# Tunnel configuration (optional)
# tunnel_name: "your_tunnel_name"
